FROM	frrouting/frr

RUN		apk update && apk add iproute2 busybox

COPY	p2/p2-router* /tmp/.
COPY	p3/p3-router* /tmp/.
COPY	./vtysh.conf.sample /etc/frr/vtysh.conf
RUN		sed -i 's/bgpd=no/bgpd=yes/g; \
				s/ospfd=no/ospfd=yes/g; \
				s/isisd=no/isisd=yes/g;' /etc/frr/daemons 
